### ISSUE TITLE
Column placed in a wrong position When dragging and changing position of the columns

### ISSUE THREAD

**Issue by sameeraroshan** [TonyGermaneri/canvas-datagrid#115] opened 2018-03-02 10:27 UTC
v0.20.5

column ended up in a wrong position when  when i try to change the position by dragging.

**Comment by TonyGermaneri** [comment] 2018-03-02 19:08
I can't reproduce the bug.  I see columns order-drag correctly when I click on the column header and drag it over another column.  I see them reorder correctly after I've reordered them as well.  Can you provide an example?

**Comment by TonyGermaneri** [comment] 2018-03-06 19:09
Is this fixed in 0.20.9?  I was never able to reproduce it.

**Comment by sameeraroshan** [comment] 2018-03-07 05:15
yes this issue is fixed in 0.20.9. you may close it.

**Closed** 2018-03-19 19:24 UTC
