### ISSUE TITLE
Moving the mouse while scrolling in Safari scrolls the full page

### ISSUE THREAD

**Issue by tim-vandecasteele** [TonyGermaneri/canvas-datagrid#285] opened 2020-08-12 13:29 UTC
### Expected behavior and actual behavior.

When scrolling a bigger table in a page (for example use the [XHR example in tutorials](https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Get-data-via-XHR-function.), that has quite some data and is in a page), I would expect only the table to scroll and not the page itself.

In Safari when you scroll and move the mouse at the same time (you almost automatically do that with a magic mouse, and on a trackpad this also happens often), the whole page moves while scrolling also happens.

The gif below doesn't do the scrolling justice, as it's way more annoying than you would think from the looks of this.

![scrolling_safari](https://user-images.githubusercontent.com/556191/90020663-6d0aca80-dcb0-11ea-876a-b125a0baed94.gif)

### Steps to reproduce the problem.

Scroll in Safari and move the mouse at the same time.

### Specifications like the version of the project, operating system, or hardware.

Safari Version 13.1.1 (15609.2.9.1.2)
MacOS Catalina

**Comment by TonyGermaneri** [comment] 2020-08-12 17:19
That isn't expected.  Scroll operations call `e.preventDefault()` which is supposed to stop that from happening.  I just checked mouse scrolling and it works correctly, so this might have something to do with trackpads or magic mouse.  I see your video very well, so I can see there is some sort of defect, further investigations need to be taken using the mouse/hardware in question here as "standard" hardware does not reproduce the defect.  I'm guessing it only affects your specific hardware setup (which is a quite common setup).  This looks like a bug, and it seems like it needs to be fixed by someone who can reproduce the issue.

For whatever reason, the scrolling event being fired here is not honoring the `e.preventDefault()` or the code path is not executing it (seems unlikely).  It might even be an OS setting.

**Comment by tim-vandecasteele** [comment] 2020-08-12 18:27
Hi @TonyGermaneri thanks for the comment, I'm definitely willing to have a shot at this myself. Could you point me in the proper direction where the scrolling is handled?

**Comment by tim-vandecasteele** [comment] 2020-08-12 18:36
In the meantime I did find that if I comment out this line in events.js:
```
if (wheeling) {
     return;
}
```
the problem disappears. 

But that also seems to have the effect that you can't scroll past the canvas.

**Comment by tim-vandecasteele** [comment] 2020-08-12 18:44
@TonyGermaneri I played a bit around with it, this seems to fix the issue, but I'm way too inexperienced in this code to know if this will have other effects. Let me know what I should test or how I can help to get more confidence about this.

**Comment by TonyGermaneri** [comment] 2020-08-12 18:46
Thanks for the quick update.  I'll check out the PR later today, stuck in meetings most of the day today.

**Comment by TonyGermaneri** [comment] 2020-08-18 20:43
No, I haven't looked at it yet, been super swamped with work.  My only concern is that standard mice, wheels and touch scrolling still work and when the scroll limits are reached the parent element can continue to scroll.  If all of this works then I'm happy to merge.

**Comment by ndrsn** [comment] 2020-12-09 00:16
Closing because PR has been merged.

**Closed by ndrsn** 2020-12-09 00:16 UTC
Labels: bug
