### ISSUE TITLE
SyntaxError: Syntax error at Grid (eval code:1:12155) when initializing canvasDatagrid object in Internet Explorer 11

### ISSUE THREAD

**Issue by kasjerJanusz** [TonyGermaneri/canvas-datagrid#227] opened 2019-06-18 15:40 UTC
### Expected behavior and actual behavior.
I get .csv file as a byte-array/arraybuffer from backend.
What I want, is to convert it to Excel spreadsheet and visualize in some element.

What I get, is converted to spreadsheet data cannot be visualized, because in Chrome after canvas grid loads, it results in just a black empty screen with default Chrome's crash icon inside, but in Internet Explorer 11 it can't even load, because code breaks on canvasDatagrid() initialization. See error from topic.

I guess it has to do something with a fact that Grid object uses some ES6 code not supported in IE11, like window.customElements, thus CustomElementRegistry.

### Steps to reproduce the problem.

```
const bufferObj = new Uint8Array(data);
const csvObj = this.XLSX.read(bufferObj, {type:"array"});
const jsonObj = this.XLSX.utils.sheet_to_json(csvObj.Sheets[csvObj.SheetNames[0]], {header: ["Header 1", "Header 2", "Header 3"], raw: false});
var previewGrid = this.canvasDataGrid();
previewGrid.data = jsonObj;
this.$document[0].getElementById('grid').appendChild(previewGrid);
```
`this.canvasDataGrid` is reference to `window.canvasDatagrid`, which in dev console returns `function(e){return new Grid(e)}` so reference is fine.

Also, what is the recommended way of visualizing spreadsheet in new scaled window, read-only?
This code don't work as expected, but opens new window, with 'about:blank' url and '[object HTMLElement]' text inside white, blank window:
```this.$window.open(`${this.url}${fileName}`, 'C-Sharpcorner', 'width=1000,height=800').document.write(previewGrid);```

### Specifications like the version of the project, operating system, or hardware.
AngularJS 1.5.8

**Comment by TonyGermaneri** [comment] 2019-06-18 18:30
It sounds like you're loading a lot of data and chrome is taking too long to draw the first frame.  You need to limit the size of the element prior to adding data to it.  `previewGrid.style.height = "100%";` and perhaps width too.  By default the grid will expand to fit the data that is inside of it (sort of like table element) if this data is too big, it will crash the browser.  To stop that, clip the visible data.  The grid code will only try and access/draw the bits of data currently visible to the DOM, not the browser window, it will draw outside of the browser window by design.

As far as the IE11 problem.  The grid does have es6 code in it, but it is encapsulated inside of a string then eval'ed at run time to allow for it to run on IE11 (or any es5).  It could be a bug, but I think it might be the same problem as chrome, but IE is just nasty about how it deals with it.  Try getting it to work in chrome first, it's known to work there, then move to IE.

Sorry you're having problems.

Cheers,
Tony

**Comment by ndrsn** [comment] 2021-02-04 20:35
Hi, I'm closing this issue, as we've dropped support for IE11.

**Closed by ndrsn** 2021-02-04 20:35 UTC
Labels: question
