### ISSUE TITLE
expanded tree not usable on last Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by lamarquenet** [TonyGermaneri/canvas-datagrid#251] opened 2020-02-11 21:11 UTC
Expected behavior:
When i expand a tree using canvas data grid the resulted tree cells can be selected and interacted.
 
Actual behavior:
 Since the new version of chrome 80.0.3987.87 you cannot select rows from the expanded tree, only from the main grid.

Observations:
I try this in many different computers, the expanded tree always worked on the older versions of chrome but it never work on the new versions.

Steps to reproduce the problem.
1) Open this page [https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Allow-users-to-open-trees] with the chrome browser updated to the last version 80.0.3987.87.
2) Click Execute for the code to run
3) Expand one of the rows 
3) Click on the expanded tree, observe the issue as nothing happens and no row is selected.

![expandTree](https://user-images.githubusercontent.com/35860662/74279434-abbbca00-4cf9-11ea-8ec1-a645a87224c5.jpg)

**Comment by TonyGermaneri** [comment] 2020-02-11 21:21
Well, that sucks.  Looks like something to do with the synthetic event bubbling.  For sure a new bug.

**Comment by lamarquenet** [comment] 2020-02-12 14:43
yes that does sucks, any estimation on when a solution to this issue could be release. I´m currently using this functionality and now is not working anymore in any of the browsers.

**Comment by TonyGermaneri** [comment] 2020-02-12 23:17
I wish I could say I can fix it ASAP, but I can't, I'm backlogged at work.  I can help and point you in the right direction to fix it though.  Best I can do is say I can look at it this weekend and figure out what the next step is.

**Comment by lamarquenet** [comment] 2020-02-13 17:11
Allright, thanks, then let me know on Monday what you figure out this weekend on relation to this issue. Thanks a lot.

**Comment by lamarquenet** [comment] 2020-02-17 17:41
Hey Tony, any news related to this issue? Can you point me in the right direction to fix this?

**Comment by TonyGermaneri** [comment] 2020-02-17 18:47
Sorry, I didn't get to it.
This is the root of the issue: https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/events.js#L797 

Click events start here.  Each grid instance (inner grid vs. outer grid) should run this code.  It sounds like the inner grid is _not_ running this code.

Tree grids are created here: https://github.com/TonyGermaneri/canvas-datagrid/blob/aee9a2a12d43dda54d615e619b90031f37f32527/lib/publicMethods.js#L531

At this point the events are bound to the inner grid (treeGrid === inner grid in this conversation).

Which calls this constructor: 

https://github.com/TonyGermaneri/canvas-datagrid/blob/7e138110f5239c8658dee9119c815f48fc34037f/lib/main.js#L17

Which loads sub modules: https://github.com/TonyGermaneri/canvas-datagrid/blob/7e138110f5239c8658dee9119c815f48fc34037f/lib/main.js#L38

This is where events are split between parent and child.  I suspect the problem lies somewhere in here.

 https://github.com/TonyGermaneri/canvas-datagrid/blob/8ebb70d720d957ccd71d0bcbd9d9028d1782f69d/lib/dom.js#L504


I think the problem is async in nature or the parent grid "consumes" the child event because of preventing of event propagation (`e.stopPropagation()`).  Likely stopPropagation is being called when it should not be called.

Of course this is all guessing.

Each grid instance has a unique ID.  If you add console.log's to the code you should be able to see if the order of click events.  Also, it might not be "click" but "mousedown", just depends on which event you see bugged.  Probably mousedown.

If you make any progress and get stuck, please message back, I'll try to help as much as I can.  Also you can join the slack channel if you want to communicate that way.

Thanks for looking into this bug.

**Comment by TonyGermaneri** [comment] 2020-02-17 18:49
Also worth noting these tests used to pass: https://tonygermaneri.github.io/canvas-datagrid/test/tests.html and now quite a lot are failing.  I developed the whole thing on chrome too.  Thanks a lot google.

**Comment by dilansankalpa** [comment] 2020-03-03 05:52
I also faced the same issue plus some others. 
1. Mouse wheel and click scrolling is not working as well for the child grids. 
2. Popup dialogs opened separately those are normally closed when clicked outside, now does not closed when when clicked on the table. This happens for parent grid as well. Seems like table prevents events from propagating.

Are both from the same root cause? For the child grid issue i saw that the property hasFocus is false for childGrids. So i tried on not checking that property for mouse wheel. Am i in the correct path or should try in a different path?

**Comment by lamarquenet** [comment] 2020-03-03 16:11
1) ==> Popup dialogs opened separately those are normally closed when clicked outside, now does not closed when when clicked on the table. This happens for parent grid as well. Seems like table prevents events from propagating. 
That is a different issue.

**Comment by TonyGermaneri** [comment] 2020-03-03 19:43
These issues I believe are related to changes in chrome as the tests spontaneously started failing in chrome.  I cannot work on fixes at the moment, but I can advise.  The first step to fix all of the problems is to get the tests passing again, that will likely reveal the core issue.  It might be something really simple. 

These used to pass 100%, then something in chrome changed:
https://tonygermaneri.github.io/canvas-datagrid/test/tests.html

This test will likely reveal what all is wrong with everything:

> Should draw row selections.

The way the test works is by locating the color of a particular pixel on the canvas.  I draw crosshairs and a red dot where the check is done to help me figure out where the sample is taken from.  The sample is not where it should be and this is likely why the test is failing.  The fact the sample is not where is should be is of great concern.

The sample system works off of the canvas pixel aspect ratio, if the aspect ratio is being calculated improperly this will cause the _MOUSE LOCATION_ to be wrong too.  This of course can lead to _all_ the problems people are having.

It might be helpful to force [maxPixelRatio](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.maxPixelRatio) to 1 to test.

I'll try and work on it soon, but it would be awesome if someone could figure out why that test is failing.

**Comment by dilansankalpa** [comment] 2020-03-06 05:00
Hi Tony. When we try to directly run the test.html file only 8 tests are failing. Any idea? I'm working in a windows machine.

**Comment by dilansankalpa** [comment] 2020-03-06 05:12
Hi Tony. When we try to directly run the test.html file only 8 tests are failing. Any idea? I'm working in a windows machine.

**Comment by TonyGermaneri** [comment] 2020-03-06 05:13
That was super insightful!!  I ran it locally and I have 0 failures now.  So the issue must be around something security related.  The tests might even be a red herring since they seem to work locally.  I just checked the defect and it is not present when running locally.  (I ran `npm run build-docs` and then loaded the docs+tutorials in the browser).  I would say back to tracing the click event to see which canvas-datagrid instance is intercepting it first (should be the topmost parent) and check to see that it propagates down the datagrid stack.  Each child binds to the parents events.

Very good find!

**Comment by TonyGermaneri** [comment] 2020-03-06 05:27
This starts the mouse down event propagation

https://github.com/TonyGermaneri/canvas-datagrid/blob/8ebb70d720d957ccd71d0bcbd9d9028d1782f69d/lib/events.js#L799

@dilansankalpa I think you're on the right path.  When you click on a child grid I would expect to see the mouse events (down, click, etc.) to fire once for each grid unless a child has stopped the propagation of the event.  This is based on `self.hasFocus` which is set true here: https://github.com/TonyGermaneri/canvas-datagrid/blob/aee9a2a12d43dda54d615e619b90031f37f32527/lib/publicMethods.js#L788 (and on touch, which I don't _think_ we need to worry about)

this https://github.com/TonyGermaneri/canvas-datagrid/blob/91390afc93a817854a6227c7f8d984149fbb22b7/lib/events.js#L355

or this

https://github.com/TonyGermaneri/canvas-datagrid/blob/91390afc93a817854a6227c7f8d984149fbb22b7/lib/events.js#L467

Are likely the events that trigger getCellAt.  From my 30,000ft view I think the X/Y coordinates that are being fed to the getCellAt function are wrong or the event isn't propagating correctly.

To check the X/Y, you can turn "debug" mode on which will draw a bunch of debug info.

file:///Users/tony.germaneri/code/canvas-datagrid/docs/index.html#tutorial--Toggle-debug-data

I hope this helps.  Thanks for looking into the issue!  Figuring out that it works locally (.html file) and not on the web is critical!  I would have never tested that.

**Comment by dilansankalpa** [comment] 2020-03-06 05:50
I checked for a scenario with a single child grid in Chrome 79 and Chrome 80 for the 'mousedown' event. When clicked on child grid mousedown fies twice. First for parent, then for child. In Chrome 79 and Chrome 80 parent event object "e" was ok. But for the child event object "e" is different in Chrome 79 and Chrome 80.
Chrome 79 - e is a MouseEvent object
Chrome 80 - e.NativeEvent is the MouseEvent object.
But in the function object properties have been accessed  e.<property_name> manner. 

In the mousedown this e is passed to self.scrollGrid(e) and then to self.getLayerPos(e) and then position is taken by accessing 

pos = {
                                x: e.clientX - rect.left,
                                y: e.clientY - rect.top
                            }

so position x and y values becomes NAN.

**Comment by dilansankalpa** [comment] 2020-03-06 16:11
Hi Tony, To make it single i tried with one single test which is failing. Test is 'Should draw row selections.' in the 'Drawing' section. I ran the test in both Chrome 79 and Chrome 80. When mousedown is called in the test following function is called in test.js

`function de(el, event, args) {
        var e = new Event(event);
        Object.keys(args).forEach(function (key) {
            e[key] = args[key];
        });
        el.dispatchEvent(e);
    }`

Here the 'el' is <canvas> element. In Chrome 79, calling el.dispatchEvent(e) will fire 'self.mousedown' function in events.js. But in Chrome 80 'self.mousedown' function is not called. 

but in both Chrome 80 when i called a getEventListeners(el) for element it shows the function. But still it is not called.
![image](https://user-images.githubusercontent.com/31346023/76100632-fd9ef980-5ff2-11ea-806d-e63f3b05b7c8.png)

**Comment by TonyGermaneri** [comment] 2020-03-08 23:06
It sounds like you're very close to solving both issues, the tests failing as well as the child grid issue. 
 Getting that NaN to be a number is going to fix the problem I think.

For the tests: 
el.dispatchEvent(new Event("mousedown")) not working is stunning.  I use that in apps everywhere and it's almost entirely native code (the event has some values added to it).  And all the test is doing is changing clientX, clientY.

For the actual issue:
The mouse event being at the top level instead of within NativeEvent sounds really strange.  

https://github.com/TonyGermaneri/canvas-datagrid/blob/91390afc93a817854a6227c7f8d984149fbb22b7/lib/events.js#L799

This is where `NativeEvent` is assigned a value.  I can't see how e jumps to the top level and reports MouseEvent, super strange.

However if you see that, maybe it's as easy as locating the proper property using object refinement or an if condition?

**Comment by dilansankalpa** [comment] 2020-03-10 12:29
Hi Tony. createShadowRoot function is not available in Chrome 80. There are some places where existence of this function is checked. Removing the usages and running the tests again now getting 100% passed.

**Comment by TonyGermaneri** [comment] 2020-03-10 17:40
THANK YOU SO MUCH!! This was a huge problem.  There are a few sorting related tests failing locally, but nothing I think we need to be concerned about.

**Comment by TonyGermaneri** [comment] 2020-03-12 00:50
Things seem to work correctly now.  Is it ok to close this ticket?

**Closed** 2020-03-23 01:49 UTC
Labels: bug, high priority

**Comment by dilansankalpa** [comment] 2020-03-23 11:52
> THANK YOU SO MUCH!! This was a huge problem. There are a few sorting related tests failing locally, but nothing I think we need to be concerned about.

Sorry. I could not reply. All my issues got solved.
