### ISSUE TITLE
Not able to scroll in IE11

### ISSUE THREAD

**Issue by bahrus** [TonyGermaneri/canvas-datagrid#45] opened 2017-09-06 12:00 UTC
Grid renders nicely, but nothing happens on scrolling.

Get error:  SCRIPT5022: ScrollTop value must be a number
intf.js (895,1)

**Comment by TonyGermaneri** [comment] 2017-09-06 18:14
I have yet to validate IE 11.  I'll try and locate a copy to validate it.

**Comment by TonyGermaneri** [comment] 2017-09-06 21:02
So scrolling on IE11 and edge is completely broken.

The first part, mouse wheel scrolling, I can fix, although I'm not sure exactly what the problem is yet.  From what I can tell wheel scrolling occurs, but there are some strange behaviors. IE is blocking drawing until events finish firing (maybe?  the profiler is antiquated), which are literally the draw events, so it's a real strange situation that might require some timing tricks to overcome. That is, the wheel event should ignore input until the previous draw event finishes or something similar.

The second part of IE scroll not working is that mouse capture is not working correctly on edge, and on IE11 doesn't even try to capture.  Mouse capture scrolling is _off by default_, but is _on in the demo_ because it is full browser window.  I see it doing _something_ but it's totally not what is expected.  I have to refactor some of the capture scrolling code in issue #40 so perhaps it will go away?  Wishful thinking.  I'll validate on IE when I tackle 40 no matter and try and make sure it works like the other browsers.

Again, by default capture is off, so it probably won't be a problem for actual implementation, unless you _really need mouse capture_ (you don't) in which case don't use IE I guess.

IE10 does not work at all due to crashing on _seeing_ MutationObserver (maybe I have to prefix it with window.).  I'll fix the immediate bug and maybe it'll just work, the program mostly just draws lines on a canvas afterall, but there are no plans on supporting IE10.

**Comment by TonyGermaneri** [comment] 2017-09-07 00:30
Ok, I've fixed the wheel problem and improved performance generally while using the wheel not just in IE/edge but all browsers.

I've found a way to double the performance of the scroll draw, this helps the problem a lot.  The core 2D context methods: fillText, strokeRect and fillRect are very slow in IE11/Edge.  To give a comparison: chrome 6ms, safari 9ms, firefox 14ms, edge 107ms.  I can only hope they improve this performance, as these core canvas drawing methods are at the very core of the program's theory and cannot be replaced.

The problem was that when events come in faster than the grid can update the drawing.  Processing the back queue blocks the UI from drawing updates until all events have fired.  To overcome that I've added a semi-debounce function to the wheel scroll method.  Before it would sync scroll and draw, now it checks first if another wheel scroll draw is pending and if so discards the incoming event.  This continuously truncates the event queue and organically keeps the number of events firing to be the number the specific browser can handle.

This makes the scroll event asynchronous which is no good, but I'll get over it.  The fix will be in the next release, probably in a few hours.

**Closed by TonyGermaneri** 2017-09-07 00:30 UTC
Labels: bug
