### ISSUE TITLE
table data change does not change icon of column header

### ISSUE THREAD

**Issue by Hybueno09** [TonyGermaneri/canvas-datagrid#217] opened 2019-05-27 15:08 UTC
### Expected behavior and actual behavior.
when I click the button named _button1_ to load new data, i expecte the arrow icon is not exists.
how should I do, thanks much

### Steps to reproduce the problem.
**Example online:**  [sandbox example](https://codesandbox.io/s/cranky-ives-m4rfb)
when I click column header such as _col1_,the table column is sorted.Then I click the button named _button1_ to load new data then render it.But the arrow icon is still exists.

**Comment by TonyGermaneri** [comment] 2019-05-29 19:23
This is the same as issue #215. The problem will be fixed shortly.  Very sorry.

**Comment by jswolf19** [comment] 2019-05-30 14:52
@TonyGermaneri The same behavior occurs if a filter is applied to the data. The sort state is reset. The current sort state does not look like it is being saved in memory like the filter state is. I think the sort state should be saved, and then reapplied when necessary. #219 does not currently address the sort problem, only the filter problem, but I can look into it if you're not already working on it.

**Comment by jswolf19** [comment] 2019-06-01 08:48
@TonyGermaneri This one's going to be more difficult to do preserving current behavior while reapplying the current sort after a data reload or filter change. Currently, `order` allows a program to supply a custom `sortFunction`, so theoretically even multiple sorts on the same column can result in a different order than just applying the last sort operation. I believe this means I would need to keep all sort functions applied over the lifetime of the grid to get the same ordering, which isn't a good idea...

I want to propose keeping only the last sort per column as a first step. This will preserve the current behavior when sorting on multiple columns without worrying about keeping all of the history. I will keep track of the sort information internally for now, but it might be a good thing to expose in the public interface in the long run.

I would also propose as a further step (in the future) that the `sortFunction` argument should be dropped from `order` and only allowing it to be defined on the type or the column schema. I'm not sure what is gained by taking it as an argument, and I feel this would better unify the sorting, filtering, and formatting APIs. I will, however, honor the current APIand keep the function that was ultimately used to sort when fixing this issue.

**Comment by TonyGermaneri** [comment] 2019-06-06 18:24
I'm ok with exposing as many internals as is useful, I primarily keep stuff hidden so examination of the object isn't annoying.

I think only maintaining the last sort function for a given column is appropriate, but allowing for sorting multiple columns is important for certain data views, even though it's not supported by the UI.

What about replacing the argument with an event?  `columnsort` or something that gets called on every cell... that could be expensive.

I'm not even sure why someone would apply more than one sort function to the same column.  I don't think that's a valid use case.  If you really wanted to apply two sorts to the data you could do that within the same function - I think.

Was there anything about the multi column sorting besides the "same column" sorting that seems like a blocker for maintaining sort state?

If it makes sense, I'm ok with breaking the interface contract, we just need to tick a big version number so people know there's contract change.

**Comment by jswolf19** [comment] 2019-06-07 11:39
> I'm not even sure why someone would apply more than one sort function to the same column. I don't think that's a valid use case. If you really wanted to apply two sorts to the data you could do that within the same function - I think.

This is what I'm thinking, too 

> I think only maintaining the last sort function for a given column is appropriate, but allowing for sorting multiple columns is important for certain data views, even though it's not supported by the UI.

I definitely want to preserve this ability. I plan to keep a list of column name, direction, and sort function to reapply as necessary. I am curious as to how reapplication will affect performance... I imagine I'll want to keep a sorted array of indices for all columns to boost perf, but I'll make that a second, distinct step.

> Was there anything about the multi column sorting besides the "same column" sorting that seems like a blocker for maintaining sort state?

1. I have an idea of how I want to maintain sort state with the `beforesortcolumn` and `sortcolumn` events, but I do want to make sure you agree with it:

- If `preventDefault()` is called in `beforesortcolumn`, then I don't need to preserve the current sort information. I'm not sure if I like this, but currently, `orderBy` is set after `beforesortcolumn`, so I'm opting to remain consistent. I can see a case for preserving unconditionally, though.

- When the sort is reapplied, I will not dispatch `beforesortcolumn`. If 1. changes, then this will change, too, though.

- When the sort is reapplied, I will dispatch `sortcolumn` at the very end, after all sorts have been applied. This way, I can combine all sort functions and effectively do one sort, which should help some with perf.

2. The [error check if the column exists](https://github.com/TonyGermaneri/canvas-datagrid/blob/6edd7c2295e82ee051e472580f2abdf963054518/lib/publicMethods.js#L646-L648) occurs after dispatching `beforesortcolumn` and after setting `orderBy`. Since filter didn't have an error check, I'm not sure if this one is necessary, but if you want to keep it, it might make more sense to do it before setting `orderBy`.

> I'm ok with exposing as many internals as is useful, I primarily keep stuff hidden so examination of the object isn't annoying.

I think eventually it will be useful to know what columns are currently being sorted on and in what order, but I think the shape of that API should be discussed more separately before exposing it. I have a couple of ideas of how it could be done, but someone else might come up with an even more convenient way ^_^

> If it makes sense, I'm ok with breaking the interface contract, we just need to tick a big version number so people know there's contract change.

I think being able to set the sort function by type or by column on the schema gives plenty of flexibility, but I may just not be creative enough ^^. I did notice that the sorter function on the column is not used in the `order` function, though, so that may need to be fixed. I also feel that the sorting is a little complicated by having the sorter function return a function to do the actual sorting. I think it might be easier to just require a function for regular sort order and reverse the result if a descending sort is required. At any rate, as above, I want to prioritize fixing the current problem before worrying about making changes that could affect current users.

**Comment by jswolf19** [comment] 2019-06-08 03:40
`rowOrder` may also be a complication eventually... `order` does not appear to set `rowOrder`, and so it is reapplied after the sort. I'm going to ignore it for now, but I think it makes more sense for it to reflect the sort. I'm also not sure if the way that `rowOrder` works with filters is intuitive, either...

I think the indices of `rowOrder` should be on the original data, with the `data` property either reflecting all filters and sorting (including reordering by `rowOrder`), or the `data` property should be the original data, rather than the data after filters and sorting are applied... Now, only some things are applied to `data`, so it can neither be used as the original data nor as a view into the data as the grid is using it.

**Comment by ndrsn** [comment] 2021-02-05 16:26
@jswolf19 and @Hybueno09 , in the interest of a very early spring cleaning I am closing this issue, as it's been marked duplicate of #215, it's been nearly two years since the last activity on it, and I'm not sure which parts of this issue are still relevant.

But please feel free to re-open if you feel it should remain so.

**Closed by ndrsn** 2021-02-05 16:26 UTC
Labels: bug, duplicate
